# Linear Algebra

- `Numpy` is a python package that can be used for Linear Algebra calculations. 
- We can use NumPy to create Vectors and Matrices in Python. 
- You don’t need any special packages to create Scalar, since it’s just a number.

From [Exploring Linear Algebra with Python](https://mubaris.com/posts/linear-algebra/).

In [21]:
import numpy as np

### Scalars

In [31]:
s = 32 # Scalar

(2, 3)
(3, 2)


### Vectors 

To creat a vector simply surround a python list `([1,2,3])` with the `np.array` function:

In [35]:
a = np.array([1, 2, 3])  # Vectors
b = np.array([3, 4, 5])  
x_vector = np.array([1,2,3])
print(x_vector)

[1 2 3]


We could have done this by defining a python list and converting it to an array:

In [37]:
c_list = [1,2]
print("The list:",c_list)
print("Has length:", len(c_list))

c_vector = np.array(c_list)
print("The vector:", c_vector)
print("Has shape:",c_vector.shape)

The list: [1, 2]
Has length: 2
The vector: [1 2]
Has shape: (2,)


In [39]:
z = [5,6]
print("This is a list, not an array:",z)
print(type(z))
zarray = np.array(z)
print("This is an array, not a list",zarray)
print(type(zarray))

This is a list, not an array: [5, 6]
<class 'list'>
This is an array, not a list [5 6]
<class 'numpy.ndarray'>


### Matrices

In [33]:
A = np.array([           # Matrices
    [3, 5, 7],
    [4, 6, 8]
])
B = np.array([
    [4, 7],
    [5, 8],
    [6, 9]
])
print(A.shape) # # Size of the Matrices
print(B.shape) # (3, 2)

(2, 3)
(3, 2)


### Addition Subtraction 

In [23]:
c = a + b # Addition of vectors
print(c)  

[4 6 8]


In [24]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
Y = np.array([
    [7, 8, 9],
    [1, 2, 3]
])
Z = X + Y # Addition of matrices
print(Z) 

[[ 8 10 12]
 [ 5  7  9]]


In [25]:
d = a - b
print(d)

[-2 -2 -2]


In [26]:
W = X - Y
print(W) # [[-6, -6, -6], [3, 3, 3]]

[[-6 -6 -6]
 [ 3  3  3]]


### Transpose of a Matrix

Transpose of a Matrix is an operator which flips a matrix over its main diagonal like a mirror image. This can be done by calling `numpy.transpose` function or `T` method in `numpy`.

In [17]:
print(X.T) 
print(np.transpose(Y))

[[1 4]
 [2 5]
 [3 6]]
[[7 1]
 [8 2]
 [9 3]]


In [18]:
print(X.shape)
print(X.T.shape)

(2, 3)
(3, 2)


In [19]:
print(Y.shape)
print(np.transpose(Y).shape)

(2, 3)
(3, 2)


###  product of arrays


`NumPy` uses `numpy.dot` function for multiplication of both vectors and matrices. Matrix multiplication is not commutative.


`numpy.dot(a, b)` Dot product of two arrays:

- If both `a` and `b` are 1-D arrays, it is inner product of vectors (without complex conjugation).
- If both `a` and `b` are 2-D arrays, it is matrix multiplication, but using `matmul` or `a @ b` is preferred.
- If either `a` or `b` is 0-D (scalar), it is equivalent to multiply and using `numpy.multiply(a, b)` or `a*b` is preferred.
- If `a` is an N-D array and `b` is a 1-D array, it is a sum product over the last axis of `a` and `b`.
- If `a` is an N-D array and `b` is an M-D array (where M>=2), it is a sum product over the last axis of `a` and the second-to-last axis of `b`:



In [76]:
# Vectors
e = np.dot(a, b)
f = np.dot(b, a)
print(e) # 26
print(f) # 26

# Matrices
C = np.dot(A, B)
C = A @ B # prefered
D = np.dot(B, A)
D = B @ A # prefered
E = np.dot(e, A)
E = e * A # prefered
print(C) # [[79, 124], [94, 148]]
print(D) # [[40, 62, 84], [47, 73, 99], [54, 84, 114]]
print(E)

# Size of C and D
print(C.shape) # (2, 2)
print(D.shape) # (3, 3)

# Vectors and Matrices
g = np.dot(A, b) # [64, 76]

26
26
[[ 79 124]
 [ 94 148]]
[[ 40  62  84]
 [ 47  73  99]
 [ 54  84 114]]
[[ 78 130 182]
 [104 156 208]]
(2, 2)
(3, 3)
[[ 78 130 182]
 [104 156 208]]


In [45]:
A*2  # = 2*A

array([[ 6, 10, 14],
       [ 8, 12, 16]])

In [56]:
A * B.T  # term to term multiplication

array([[12, 25, 42],
       [28, 48, 72]])

### Inverse

Inverse operation only applies to square matrices. To compute inverse using numpy we need to use `numpy.linalg.inv` function

In [28]:
P = np.array([
    [1, 3, 3],
    [1, 4, 3],
    [1, 3, 4]
])
Pinv = np.linalg.inv(P)
print(Pinv)

[[ 7. -3. -3.]
 [-1.  1.  0.]
 [-1.  0.  1.]]


### Special matrices

In [29]:
# Identity Matrix of size (3, 3)
I3 = np.identity(3)
# Identity Matrix of size (2, 2)
I2 = np.identity(2)

# Zero Matrix
Q = np.zeros((3, 2)) # Size (3, 2)
R = np.zeros((5, 6)) # Size (5, 6)

### Determinant

In [30]:
A = np.array([
    [1, 3, 3],
    [4, 5, 6],
    [7, 8, 9]
])
B = np.array([
    [34, 54],
    [67, 87]
])

adet = np.linalg.det(A)
bdet = np.linalg.det(B)

print(adet) # 6.0
print(bdet) # -660.0

6.000000000000003
-659.9999999999993


### Rank

In [84]:
A = np.ones((4,3))
print(A)
np.rank(A)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


/Users/campillo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  This is separate from the ipykernel package so we can avoid doing imports until


2

In [85]:
A.ndim

2

### Solve `Ax = b`


In [86]:
from numpy.linalg import solve
A = np.array([[1,2],[3,4]])
b = np.array([10, 20])
x = solve(A,b)

In [87]:
A @ x - b

array([0., 0.])

### eigen values and vectors

In [90]:
from numpy.linalg import eig
A = np.array([[1,2],[3,4]])
eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

The eig returns two tuples: the first one is the eigen values and the second one is a matrix whose columns are the two eigen vectors.

We can unpack the tuples:

In [91]:
eigen_val, eigen_vec = eig(A)  # unpack the tuples
print(eigen_val)
print(eigen_vec)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
